services:
  actual_server:
    container_name: actual
    image: docker.io/actualbudget/actual-server:25.5.0@sha256:3b486fbc0db02839917f65ed277aa509980f710b6e96dde966f5219983978179
    ports:
      - $ACTUAL_SERVER_PORT:5006
    volumes:
      - $ACTUAL_SERVER_VOL_DATA:/data
    restart: unless-stopped
