services:
  actual_server:
    container_name: actual
    image: docker.io/actualbudget/actual-server:25.6.0@sha256:224014dd009a57df7e02e8343bc216b2bd143ec10683a3c1de36cadee7553e56
    ports:
      - $ACTUAL_SERVER_PORT:5006
    volumes:
      - $ACTUAL_SERVER_VOL_DATA:/data
    restart: unless-stopped
