services:
  freshrss:
    container_name: freshrss
    image: lscr.io/linuxserver/freshrss:1.29.1@sha256:926526335b869ea4bef79275fb6151dd8a3fc95ce19de3f0cc32a45a5dc22e36
    environment:
      - PUID=$FRESH_RSS_PUID
      - PGID=$FRESH_RSS_PGID
      - TZ=$FRESH_RSS_TZ
    volumes:
      - $FRESH_RSS_VOL_CONFIG:/config
    ports:
      - $FRESH_RSS_PORT:80
    networks:
      - proxy
      - internet
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
