services:
  freshrss:
    container_name: freshrss
    image: lscr.io/linuxserver/freshrss:1.29.1@sha256:7ba33d8d9721c2a27bba7780e6072c004c477b9ad27ee770eab5d60c834de0d0
    environment:
      - PUID=$FRESH_RSS_PUID
      - PGID=$FRESH_RSS_PGID
      - TZ=$FRESH_RSS_TZ
    volumes:
      - $FRESH_RSS_VOL_CONFIG:/config
    ports:
      - $FRESH_RSS_PORT:80
    networks:
      - proxy
      - internet
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
