services:
  freshrss:
    container_name: freshrss
    image: lscr.io/linuxserver/freshrss:1.29.1@sha256:1325365f3b9002d76251aef82505ce0e56c00ecc2790ce351b2fb1cc858a4278
    environment:
      - PUID=$FRESH_RSS_PUID
      - PGID=$FRESH_RSS_PGID
      - TZ=$FRESH_RSS_TZ
    volumes:
      - $FRESH_RSS_VOL_CONFIG:/config
    ports:
      - $FRESH_RSS_PORT:80
    networks:
      - proxy
      - internet
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
