services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2026.6.0.dev202605160317@sha256:6a7a60cd4f4c47521ccc86d31a1922dc36f2575a66b422491233302271b9d9e2
    ports:
      - $HOME_ASSISTANT_PORT:8123
    networks:
      - proxy
      - iot-intra
    environment:
      - TZ=$HOME_ASSISTANT_TZ
    volumes:
      - $HOME_ASSISTANT_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped

networks:
  proxy:
    external: true
  iot-intra:
    external: true
