services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2025.4.0.dev202503150230@sha256:143af62ad9302def937e94bb72f90ee934d3453c23ed2684624b3dab42d66b73
    privileged: true
    ports:
      - $HOME_ASSISTANT_PORT:8123
    environment:
      - TZ=$HOME_ASSISTANT_TZ
    volumes:
      - $HOME_ASSISTANT_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    network_mode: host
    restart: unless-stopped
