services:
  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:2026.7.0.dev202605310321@sha256:ee81651c8d45b2d6f9be64460b244c52b911a91a0a2f21631768ce181a76fd63
    ports:
      - $HOME_ASSISTANT_PORT:8123
    networks:
      - proxy
      - iot-intra
    environment:
      - TZ=$HOME_ASSISTANT_TZ
    volumes:
      - $HOME_ASSISTANT_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped

networks:
  proxy:
    external: true
  iot-intra:
    external: true
