services:
  broker:
    image: docker.io/library/redis:7.4.2-alpine3.21
    container_name: paperless-redis
    volumes:
      - $PAPERLESS_NGX_REDIS_VOL_DATA:/data
    restart: unless-stopped
  db:
    image: docker.io/library/postgres:17.3-alpine3.21
    container_name: paperless-db
    volumes:
      - $PAPERLESS_NGX_DB_VOL_DATA:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=$PAPERLESS_NGX_DB_USER
      - POSTGRES_PASSWORD=$PAPERLESS_NGX_DB_PASSWORD
    restart: unless-stopped
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.14.7
    container_name: paperless-gnx
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - $PAPERLESS_NGX_PORT:8000
    volumes:
      - $PAPERLESS_NGX_VOL_DATA:/usr/src/paperless/data
      - $PAPERLESS_NGX_VOL_MEDIAS:/usr/src/paperless/media
      - $PAPERLESS_NGX_VOL_EXPORT:/usr/src/paperless/export
      - $PAPERLESS_NGX_VOL_CONSUME:/usr/src/paperless/consume
    environment:
      - USERMAP_UID=$PAPERLESS_NGX_PUID
      - USERMAP_GID=$PAPERLESS_NGX_PGID
      - PAPERLESS_URL=$PAPERLESS_NGX_URL
      - PAPERLESS_SECRET_KEY=$PAPERLESS_NGX_SECRET
      - PAPERLESS_TIME_ZONE=$PAPERLESS_NGX_TZ
      - PAPERLESS_OCR_LANGUAGE=$PAPERLESS_NGX_OCR_LANGUAGE
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      - PAPERLESS_DBUSER=$PAPERLESS_NGX_DB_USER
      - PAPERLESS_DBPASS=$PAPERLESS_NGX_DB_PASSWORD
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
    restart: unless-stopped
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.17.1
    container_name: paperless-gotenberg
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: unless-stopped
  tika:
    image: docker.io/apache/tika:3.1.0.0
    container_name: paperless-tika
    restart: unless-stopped
