services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7@sha256:c9bdf96db6d206272a69edcfc54e771190dc8b4f6a6c2bb2e4d91f485824e470
    container_name: jellyfin
    ports:
      - $JELLYFIN_PORT:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - proxy
      - internet
    environment:
      - PUID=$JELLYFIN_PUID
      - PGID=$JELLYFIN_PGID
      - TZ=$JELLYFIN_TZ
      - JELLYFIN_PublishedServerUrl=$JELLYFIN_URL
    volumes:
      - $JELLYFIN_VOL_CONFIG:/config
      - $JELLYFIN_VOL_MEDIAS:/media:ro
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
