services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.8@sha256:e622a48adf7193c7d626c2325a40f9b01c932c8e7bf3f50ffa40e7e9b6ce1d39
    container_name: jellyfin
    ports:
      - $JELLYFIN_PORT:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - proxy
      - internet
    environment:
      - PUID=$JELLYFIN_PUID
      - PGID=$JELLYFIN_PGID
      - TZ=$JELLYFIN_TZ
      - JELLYFIN_PublishedServerUrl=$JELLYFIN_URL
    volumes:
      - $JELLYFIN_VOL_CONFIG:/config
      - $JELLYFIN_VOL_MEDIAS:/media:ro
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
