services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.3@sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027
    container_name: gluetun
    ports:
      - $TRANSMISSION_VPN_PORT:9091
      - $DISPATCHARR_PORT:9191
    networks:
      - proxy
      - internet
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - $TRANSMISSION_VPN_VOL_DATA:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=$TRANSMISSION_VPN_PROVIDER
      - OPENVPN_USER=$TRANSMISSION_VPN_USER
      - OPENVPN_PASSWORD=$TRANSMISSION_VPN_PASSWORD
      - SERVER_REGIONS=$TRANSMISSION_VPN_REGION
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTPPROXY=off
      - FIREWALL_INPUT_PORTS=9091,9191
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission:amd64-4.1.3-r0-ls356@sha256:16671b2b6a76141b5fada1667221811fb04fddf43ca73277a92c48d1969640ad
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=$TRANSMISSION_PUID
      - PGID=$TRANSMISSION_PGID
      - TZ=$TRANSMISSION_TZ
    volumes:
      - $TRANSMISSION_VOL_CONFIG:/config
      - $TRANSMISSION_VOL_INIT:/custom-cont-init.d:ro
      - $TRANSMISSION_VOL_DOWNLOADS:/downloads
      - $TRANSMISSION_VOL_MEDIAS:/mnt/medias
    depends_on: 
      - gluetun
    network_mode: "service:gluetun"

networks:
  proxy:
    external: true
  internet:
    external: true
