services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.4.0-nightly@sha256:9ec633c2dc47bede5db25dfe064da270c2c2c6f08a745b8d85b185077161f2c7
    container_name: prowlarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_PROWLARR_VOL_CONFIG:/config
    ports:
      - $ARR_STACK_PROWLARR_PORT:9696
    networks:
      - proxy
      - internet
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.21@sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b
    container_name: flaresolverr
    environment:
      - TZ=$ARR_STACK_TZ
    networks:
      - internet
    restart: unless-stopped 
  radarr:
    image: linuxserver/radarr:6.2.0-nightly@sha256:00fb6c6133d0b8df625f99bcf27496ec2e12dc7e63da18fc909a8a401775a88f
    container_name: radarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_RADARR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_RADARR_PORT:7878
    networks:
      - proxy
      - internet
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:4.0.16.2944-ls299@sha256:60e5edcac39172294ad22d55d1b08c2c0a9fe658cad2f2c4d742ae017d7874de
    container_name: sonarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_SONARR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_SONARR_PORT:8989
    restart: unless-stopped
    networks:
      - proxy
      - internet
  readarr:
    image: linuxserver/readarr:develop@sha256:db02fba99182aaa9321558b52c972a0ae75e6a6deaff59efd734ffc5efe985d5
    container_name: readarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_READARR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_READARR_PORT:8787
    networks:
      - proxy
      - internet
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.2@sha256:98296861cf3caebe8ada72e5dbe2729fb10cdb2042d2b82e86065bf870418587
    container_name: jellyseerr
    environment:
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_JELLYSEERR_VOL_CONFIG:/app/config
    ports:
      - $ARR_STACK_JELLYSEERR_PORT:5055
    networks:
      - proxy
      - internet
    restart: unless-stopped
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest@sha256:deb929e781676d6d67cfe6ca4a0efb3323a629d3eff0fed3c1c4029482b3821c
    container_name: mylar3
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_MYLAR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_MYLAR_PORT:8090
    networks:
      - proxy
      - internet
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
