services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.1-nightly@sha256:991fec758c8f583b573f0767d8bbb123626dc6845dfaaa8c6211470539ea5b22
    container_name: prowlarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_PROWLARR_VOL_CONFIG:/config
    ports:
      - $ARR_STACK_PROWLARR_PORT:9696
    networks:
      - proxy
      - internet
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
    container_name: flaresolverr
    environment:
      - TZ=$ARR_STACK_TZ
    networks:
      - internet
    restart: unless-stopped 
  radarr:
    image: linuxserver/radarr:6.4.2-nightly@sha256:ff86c2172d2662875f7984b0b23b2b4e2c934ae1cc7f99c174f91054e65d8e06
    container_name: radarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_RADARR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_RADARR_PORT:7878
    networks:
      - proxy
      - internet
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:4.0.19.2979-ls320@sha256:24acea2956a0ccb11f103877d9f4f8576600fb34bff34820ed749c2256dab89f
    container_name: sonarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_SONARR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_SONARR_PORT:8989
    restart: unless-stopped
    networks:
      - proxy
      - internet
  readarr:
    image: linuxserver/readarr:develop@sha256:db02fba99182aaa9321558b52c972a0ae75e6a6deaff59efd734ffc5efe985d5
    container_name: readarr
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_READARR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_READARR_PORT:8787
    networks:
      - proxy
      - internet
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.2@sha256:98296861cf3caebe8ada72e5dbe2729fb10cdb2042d2b82e86065bf870418587
    container_name: jellyseerr
    environment:
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_JELLYSEERR_VOL_CONFIG:/app/config
    ports:
      - $ARR_STACK_JELLYSEERR_PORT:5055
    networks:
      - proxy
      - internet
    restart: unless-stopped
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest@sha256:886f4517177932900d7626e8673f091d09686b4cda9b55cf529dfc363a2d7a8b
    container_name: mylar3
    environment:
      - PUID=$ARR_STACK_PUID
      - PGID=$ARR_STACK_PGID
      - TZ=$ARR_STACK_TZ
    volumes:
      - $ARR_STACK_MYLAR_VOL_CONFIG:/config
      - $ARR_STACK_VOL_MEDIAS:/mnt/medias
    ports:
      - $ARR_STACK_MYLAR_PORT:8090
    networks:
      - proxy
      - internet
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
