services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine@sha256:a908c65cc8e67ec9d292ef27c2c0360dbaaee7eb1b935cdd194e67697f15dea1
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    networks:
      iot-intra:
      iot:
        ipv4_address: $MOSQUITTO_IPV4
    volumes:
      - $MOSQUITTO_VOL_CONFIG:/mosquitto/config
      - $MOSQUITTO_VOL_DATA:/mosquitto/data
    restart: unless-stopped

networks:
  iot-intra:
    external: true
  iot:
    external: true
