services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    networks:
      iot-intra:
      iot:
        ipv4_address: $MOSQUITTO_IPV4
    volumes:
      - $MOSQUITTO_VOL_CONFIG:/mosquitto/config
      - $MOSQUITTO_VOL_DATA:/mosquitto/data
    restart: unless-stopped

networks:
  iot-intra:
    external: true
  iot:
    external: true
