services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.2.0@sha256:5e6bcbb595c4e857540577135e0f8b3ffc2e97c23d6e0ddc7df183de5bfdd442
    container_name: homepage
    restart: unless-stopped
    ports:
      - $HOMEPAGE_PORT:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=$HOMEPAGE_ALLOWED_HOSTS
    volumes:
      - $HOMEPAGE_VOL_CONFIG:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
    env_file: 
      - $HOMEPAGE_SECRETS_ENV_FILE_PATH
