services: 
  cloudflared: 
    image: cloudflare/cloudflared:2026.7.3@sha256:e39ee8da81ad5e05d77f38d2f51c60ca51bf2a8450ac3abab50c17fdb91d91bf
    container_name: cloudflare-tunnel 
    command: tunnel run 
    networks:
      - proxy
      - internet
    environment: 
      - TUNNEL_TOKEN=$CLOUDFLARED_TOKEN
    restart: unless-stopped

networks:
  proxy:
    external: true
  internet:
    external: true
