services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.4.0@sha256:dd7479e5416c4b95725333d0a69ff504bcbda9a7a3431e5d5dd1e27c16465cdd
    restart: unless-stopped
    privileged: true
    ports:
      - $ZIGBEE2MQTT_PORT:8080
    environment:
      - TZ=$ZIGBEE2MQTT_TZ
    volumes:
      - $ZIGBEE2MQTT_VOL_DATA:/app/data
      - /run/udev:/run/udev:ro
    group_add:
      - dialout
