services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.10.1@sha256:67c26dcf8346aced02fe1380a6afd1b57268bcef10faae3f6057c13d5d3dfa80
    restart: unless-stopped
    privileged: true
    networks:
      - iot
      - iot-intra
      - proxy
    ports:
      - $ZIGBEE2MQTT_PORT:8080
    environment:
      - TZ=$ZIGBEE2MQTT_TZ
    volumes:
      - $ZIGBEE2MQTT_VOL_DATA:/app/data
      - /run/udev:/run/udev:ro
    group_add:
      - dialout

networks:
  iot:
    external: true
  iot-intra:
    external: true
  proxy:
    external: true
