services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.6.1@sha256:22e1fc160163edee0ceef47910211e97e7b0fb18b6bc94c9b799409252409f6a
    restart: unless-stopped
    privileged: true
    ports:
      - $ZIGBEE2MQTT_PORT:8080
    environment:
      - TZ=$ZIGBEE2MQTT_TZ
    volumes:
      - $ZIGBEE2MQTT_VOL_DATA:/app/data
      - /run/udev:/run/udev:ro
    group_add:
      - dialout
