services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:1.12.0@sha256:005ec623508758228f9e856174a100be1bc4a9e3b7af9e00ae3215b0afde3d05
        container_name: speedtest-tracker
        restart: unless-stopped
        ports:
            - $SPEEDTEST_TRACKER_PORT:80
        environment:
            - PUID=$SPEEDTEST_TRACKER_PUID
            - PGID=$SPEEDTEST_TRACKER_PGID
            - TZ=$SPEEDTEST_TRACKER_TZ
            - APP_KEY=$SPEEDTEST_TRACKER_KEY
            - APP_URL=$SPEEDTEST_TRACKER_URL
            - DB_CONNECTION=$SPEEDTEST_TRACKER_DB_TYPE
        volumes:
            - $SPEEDTEST_TRACKER_VOL_CONFIG:/config
