services:
    vaulwarde:
        container_name: vaultwarden
        image: vaultwarden/server:1.33.0-alpine
        ports:
            - $VAULTWARDEN_PORT:80
        environment:
            - DOMAIN=$VAULTWARDEN_URL
            - SIGNUPS_ALLOWED=$VAULTWARDEN_SIGNUP_ALLOWED
        volumes:
            - $VAULTWARDEN_VOL_DATA:/data
        restart: unless-stopped
