services:
    vaulwarde:
        container_name: vaultwarden
        image: vaultwarden/server:1.33.0-alpine@sha256:aae674bfa22cd21bb714a18d5d832984b34275272512984fc0dc62ea6cca6133
        ports:
            - $VAULTWARDEN_PORT:80
        environment:
            - DOMAIN=$VAULTWARDEN_URL
            - SIGNUPS_ALLOWED=$VAULTWARDEN_SIGNUP_ALLOWED
        volumes:
            - $VAULTWARDEN_VOL_DATA:/data
        restart: unless-stopped
