services:
    vaulwarde:
        container_name: vaultwarden
        image: vaultwarden/server:1.33.2@sha256:87edb99945da91bd7504ac1435495595af2e89ad2c7adc151ae5bf091ec8baf2
        ports:
            - $VAULTWARDEN_PORT:80
        environment:
            - DOMAIN=$VAULTWARDEN_URL
            - SIGNUPS_ALLOWED=$VAULTWARDEN_SIGNUP_ALLOWED
        volumes:
            - $VAULTWARDEN_VOL_DATA:/data
        restart: unless-stopped
