services:
  vaulwarde:
    container_name: vaultwarden
    image: vaultwarden/server:1.34.3@sha256:84fd8a47f58d79a1ad824c27be0a9492750c0fa5216b35c749863093bfa3c3d7
    ports:
      - $VAULTWARDEN_PORT:80
    networks:
      - proxy
    environment:
      - DOMAIN=$VAULTWARDEN_URL
      - SIGNUPS_ALLOWED=$VAULTWARDEN_SIGNUP_ALLOWED
    volumes:
      - $VAULTWARDEN_VOL_DATA:/data
    restart: unless-stopped

networks:
  proxy:
    external: true
